# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3fddab3f62d3ab3d3010c27c1a6f0f99e5c327bc4dfa5e620d0cf7f20cd6fe9c8caef4597db3527dff9c4bfccdc2694c0361915062a27ac423986fe5bca82fe

test:
  secret_key_base: a32039e84a4d5923fb098d27a551e36666a3b0c543573f4fa8212d2417dd35fac992632b9df017ae04c5231a4c87b949ef8ed4947a94fe0692585971b8b46331

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
